### ISSUE TITLE
Error: NotFound message

### ISSUE THREAD

**Issue by LeG3nDz** [zaggino/brackets-snippets#22]
Hi :)

After a new installation of Brackets, I have an error message to the software launch :

    Error: NotFound
    at toError (file:///C:/Users/Stephane/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-snippets/src/ErrorHandler.js:13:16)
    at Object.show (file:///C:/Users/Stephane/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-snippets/src/ErrorHandler.js:17:15)
    at file:///C:/Users/Stephane/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-snippets/src/Snippets.js:142:34
    at FileSystem.eval (/filesystem/FileSystem.js:603:21)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:232:17)

I tried to remove the extension and reinstalling, but the message is still present.

Do you have an idea to solve the problem ?

Thank you :)

**Comment by zaggino** [comment]
Hi, I have no idea what was `NotFound` ... can you provide detailed debug logs from the console? (turn debug on in git settings, restart and open console f12)

**Comment by zaggino** [comment]
Ignore previous comment, deleted it. I probably have an idea, but I'll check to be sure.

**Comment by LeG3nDz** [comment]
Hi zaggino,

Have you had time to check the problem ?

**Comment by zaggino** [comment]
Got to it now, bit low on the free time but I'll release a new version in the next few hours I hope.

**Comment by zaggino** [comment]
Please test the latest version `0.5.0` and provide feedback, thanks!

**Comment by LeG3nDz** [comment]
Hi zaggino,

Message always present when Brackets

    Error: _loadSnippetsFromDirectories: C:/Users/Stephane/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-snippets/default_snippets/js/ is not a directory!
    at toError (file:///C:/Users/str/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-snippets/src/ErrorHandler.js:13:16)
    at Object.show (file:///C:/Users/str/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-snippets/src/ErrorHandler.js:17:15)
    at file:///C:/Users/str/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-snippets/src/Snippets.js:152:34
    at FileSystem.eval (/filesystem/FileSystem.js:603:21)
    at eval (/filesystem/impls/appshell/AppshellFileSystem.js:232:17)

And, i've the 0.5.0 :

![brackets-screenshot](https://cloud.githubusercontent.com/assets/4712791/6016212/ef3f2f82-ab7e-11e4-8419-97333d5a285b.jpg)
